Repository wecode-bootcamp-korea/38-backend-westagram, pull requests merged in 2022-10, with the labels that each got.

#3 [천송인-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/cheonsongin/.env.sample
  teamB/cheonsongin/.gitignore
  teamB/cheonsongin/app.js
  teamB/cheonsongin/package-lock.json
  teamB/cheonsongin/package.json
Labels: 멘토 리뷰 요청

#9 [김택수-TeamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/kimTaeksoo/.env.sample
  teamA/kimTaeksoo/.gitignore
  teamA/kimTaeksoo/app.js
  teamA/kimTaeksoo/package-lock.json
  teamA/kimTaeksoo/package.json
Labels: 멘토 리뷰 요청

#17 [김경훈-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/KimKyoungHun/.env.sample
  teamB/KimKyoungHun/.gitignore
  teamB/KimKyoungHun/app.js
  teamB/KimKyoungHun/package-lock.json
  teamB/KimKyoungHun/package.json
Labels: 완료

#5 [정재욱-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/jungJaeUk/.gitignore
  teamB/jungJaeUk/app.js
  teamB/jungJaeUk/db/schema.sql
Labels: 완료

#25 [이현태-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/leeHyeonTae/.env.sample
  teamA/leeHyeonTae/.gitignore
  teamA/leeHyeonTae/app.js
  teamA/leeHyeonTae/package-lock.json
  teamA/leeHyeonTae/package.json
Labels: 멘토 리뷰 요청

#30 [박은송-teamB] Assignment 3: Express API - CRUD API 만들기
  teamB/eunsong/.env.sample
  teamB/eunsong/.gitignore
  teamB/eunsong/app.js
  teamB/eunsong/db/migrations/20221005064543_create_users_table.sql
  teamB/eunsong/db/migrations/20221005064612_create_posts_table.sql
  teamB/eunsong/db/migrations/20221005064623_create_likes_table.sql
  teamB/eunsong/db/migrations/20221005064636_create_comments_table.sql
  teamB/eunsong/package-lock.json
  teamB/eunsong/package.json
Labels: 완료

#26 [이현태-teamA] Assignment 2: Express API - 유저 회원가입 하기 (layered patter 적용)
  teamA/leeHyeonTae/.gitignore
  teamA/leeHyeonTae/app.js
  teamA/leeHyeonTae/controllers/userController.js
  teamA/leeHyeonTae/db/migrations/20221007151535_users.sql
  teamA/leeHyeonTae/models/userDao.js
  teamA/leeHyeonTae/package-lock.json
  teamA/leeHyeonTae/routes/index.js
  teamA/leeHyeonTae/routes/userRouter.js
  teamA/leeHyeonTae/services/userService.js
Labels: 완료

#22 [김희연-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/initial-settings-express/heeyeon/.env.sample
  teamA/initial-settings-express/heeyeon/.gitignore
  teamA/initial-settings-express/heeyeon/app.js
  teamA/initial-settings-express/heeyeon/package-lock.json
  teamA/initial-settings-express/heeyeon/package.json
Labels: 완료

#29 [김성훈-teamB] Assignment 2: Express API - 유저 회원가입 하기
  teamB/kimSungHoon/.env.sample
  teamB/kimSungHoon/.gitignore
  teamB/kimSungHoon/app.js
  teamB/kimSungHoon/db/migrations/20221007033446_create_users_table.sql
  teamB/kimSungHoon/db/migrations/20221007033458_create_posts_table.sql
  teamB/kimSungHoon/db/migrations/20221007034909_create_likes_table.sql
  teamB/kimSungHoon/db/migrations/20221007035500_create_comments_table.sql
  teamB/kimSungHoon/package-lock.json
  teamB/kimSungHoon/package.json
Labels: 멘토 리뷰 요청

#42 [정도영-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/jeongDoYoung/.env.sample
  teamA/jeongDoYoung/.gitignore
  teamA/jeongDoYoung/app.js
  teamA/jeongDoYoung/db/migrations/20221009064435_create_users_table.sql
  teamA/jeongDoYoung/db/migrations/20221009064442_create_posts_table.sql
  teamA/jeongDoYoung/db/migrations/20221009064448_create_comments_table.sql
  teamA/jeongDoYoung/db/migrations/20221009064454_create_likes_table.sql
  teamA/jeongDoYoung/package-lock.json
  teamA/jeongDoYoung/package.json
Labels: 멘토 리뷰 요청

#38 [김택수-teamA] Assignment 3: Express API - CRUD
  teamA/kimTaeksoo/.env.sample
  teamA/kimTaeksoo/.gitignore
  teamA/kimTaeksoo/app.js
  teamA/kimTaeksoo/controller/postController.js
  teamA/kimTaeksoo/controller/userController.js
  teamA/kimTaeksoo/db/migrations/20221008010523_users_table.sql
  teamA/kimTaeksoo/db/migrations/20221008010529_posts_table.sql
  teamA/kimTaeksoo/db/migrations/20221008010536_comments_table.sql
  teamA/kimTaeksoo/db/migrations/20221008010540_likes_table.sql
  teamA/kimTaeksoo/db/migrations/20221008022106_posts_table.sql
  teamA/kimTaeksoo/db/migrations/20221010055141_likes_table_uniquecolumn.sql
  teamA/kimTaeksoo/model/postDao.js
  teamA/kimTaeksoo/model/userDao.js
  teamA/kimTaeksoo/package-lock.json
  teamA/kimTaeksoo/package.json
  teamA/kimTaeksoo/router/index.js
  teamA/kimTaeksoo/router/postRouter.js
  teamA/kimTaeksoo/router/userRouter.js
  teamA/kimTaeksoo/service/postService.js
  teamA/kimTaeksoo/service/userService.js
  teamA/kimTaeksoo/util/datasource.js
Labels: 완료

#49 [신인혁-teamB] Assignment 1: Express API - new 초기 환경 세팅
  teamB/shinInHuck/myapp/.env.sample
  teamB/shinInHuck/myapp/.gitignore
  teamB/shinInHuck/myapp/app.js
  teamB/shinInHuck/myapp/package-lock.json
  teamB/shinInHuck/myapp/package.json
Labels: 완료

#18 [천송인-teamB] Assignment 2: Express API - 유저 회원가입 하기
  package-lock.json
  teamB/cheonsongin/.gitignore
  teamB/cheonsongin/app.js
  teamB/cheonsongin/db/migrations/20221006081851_create_users_table.sql
  teamB/cheonsongin/package-lock.json
  teamB/cheonsongin/package.json
Labels: 멘토 리뷰 요청

#56 [신인혁-teamB] Assignment 1: Express API - 초기 환경 세팅 수정
  teamB/shinInHuck/myapp/.env.sample
  teamB/shinInHuck/myapp/.gitignore
  teamB/shinInHuck/myapp/app.js
  teamB/shinInHuck/myapp/package-lock.json
  teamB/shinInHuck/myapp/package.json
Labels: 완료

#11 [김성훈-teamB] Assignment 1: Express API - 초기 환경 세팅
  teamB/kimSungHoon/.env.sample
  teamB/kimSungHoon/.gitignore
  teamB/kimSungHoon/package.json
Labels: 완료

#12 [정재욱-teamB] Assignment 3: Express API - CRUD
  teamB/jungJaeUk/app.js
Labels: 완료

#43 [정해만1-teamA] Assignment 1: Express API - 초기 환경 세팅
  teamA/jeongHaeMan1/.env.sample
  teamA/jeongHaeMan1/.gitignore
  teamA/jeongHaeMan1/app.js
  teamA/jeongHaeMan1/db/migrations/20221009052820_create_users_table.sql
  teamA/jeongHaeMan1/db/migrations/20221009052843_create_posts_table.sql
  teamA/jeongHaeMan1/db/migrations/20221009052902_create_likes_table.sql
  teamA/jeongHaeMan1/package-lock.json
  teamA/jeongHaeMan1/package.json
Labels: 멘토 리뷰 요청

#50 [박은송-teamB] Assignment 1: Layered Pattern
  teamB/eunsong/.gitignore
  teamB/eunsong/app.js
  teamB/eunsong/controllers/likeController.js
  teamB/eunsong/controllers/postController.js
  teamB/eunsong/controllers/userController.js
  teamB/eunsong/models/DaoModule.js
  teamB/eunsong/models/likeDao.js
  teamB/eunsong/models/postDao.js
  teamB/eunsong/models/userDao.js
  teamB/eunsong/routes/index.js
  teamB/eunsong/routes/likeRouter.js
  teamB/eunsong/routes/postRouter.js
  teamB/eunsong/routes/userRouter.js
  teamB/eunsong/services/likeService.js
  teamB/eunsong/services/postService.js
  teamB/eunsong/services/userService.js
Labels: 멘토 리뷰 요청

#59 [박은송-teamB] Assignment 1: Error Handling
  teamB/eunsong/controllers/postController.js
  teamB/eunsong/controllers/userController.js
  teamB/eunsong/models/userDao.js
  teamB/eunsong/routes/index.js
  teamB/eunsong/services/userService.js
Labels: 멘토 리뷰 요청

#24 [이찬우-teamA] Assignment 3~8: Express API - CRUD
  teamA/leeChanWoo/app.js
  teamA/leeChanWoo/db/schema.sql
  teamA/leeChanWoo/package-lock.json
  teamA/leeChanWoo/package.json
Labels: 리뷰 진행 중

#34 [김성훈-teamB] Assignment 3: Express API - CRUD
  teamB/kimSungHoon/.env.sample
  teamB/kimSungHoon/.gitignore
  teamB/kimSungHoon/app.js
Labels: 멘토 리뷰 요청

#54 [천송인-teamB] Assignment 1: Layered Pattern
  teamB/cheonsongin/.gitignore
  teamB/cheonsongin/app.js
  teamB/cheonsongin/controllers/likeController.js
  teamB/cheonsongin/controllers/postController.js
  teamB/cheonsongin/controllers/userController.js
  teamB/cheonsongin/db/migrations/20221009060052_create_comments_table.sql
  teamB/cheonsongin/models/likeDao.js
  teamB/cheonsongin/models/postDao.js
  teamB/cheonsongin/models/userDao.js
  teamB/cheonsongin/package.json
  teamB/cheonsongin/routes/index.js
  teamB/cheonsongin/routes/likeRouter.js
  teamB/cheonsongin/routes/postRouter.js
  teamB/cheonsongin/routes/userRouter.js
  teamB/cheonsongin/services/likeService.js
  teamB/cheonsongin/services/postService.js
  teamB/cheonsongin/services/userService.js
  teamB/cheonsongin/utils/appDataSource.js
Labels: 멘토 리뷰 요청

#62 [김택수-teamA] Assignment 3: Express API - CRUD
  teamA/kimTaeksoo/app.js
  teamA/kimTaeksoo/service/postService.js
Labels: 완료

#53 [teamB-심채원]ASSIGNMENT3 - 게시글 등록하기
  teamB/simchaewon/.env.example
  teamB/simchaewon/.gitignore
  teamB/simchaewon/app.js
  teamB/simchaewon/controllers/likeController.js
  teamB/simchaewon/controllers/postController.js
  teamB/simchaewon/controllers/userController.js
  teamB/simchaewon/db/migrations/20221010055806_create_users_table.sql
  teamB/simchaewon/db/migrations/20221010055814_create_posts_table.sql
  teamB/simchaewon/db/migrations/20221010055822_create_likes_table.sql
  teamB/simchaewon/models/likeDao.js
  teamB/simchaewon/models/postDao.js
  teamB/simchaewon/models/userDao.js
  teamB/simchaewon/package-lock.json
  teamB/simchaewon/package.json
  teamB/simchaewon/routes/index.js
  teamB/simchaewon/routes/likeRouter.js
  teamB/simchaewon/routes/postRouter.js
  teamB/simchaewon/routes/userRouter.js
  teamB/simchaewon/services/likeService.js
  teamB/simchaewon/services/postService.js
  teamB/simchaewon/services/userService.js
  teamB/simchaewon/utils/typeorm.js
Labels: 멘토 리뷰 요청

#55 [김희연-teamA] Assignment 3: Express API - CRUD
  teamA/crud-express/heeyeon/.env.sample
  teamA/crud-express/heeyeon/.gitignore
  teamA/crud-express/heeyeon/app.js
  teamA/crud-express/heeyeon/db/migrations/20221006181716_create_users_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181725_create_posts_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181733_create_comments_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181738_create_likes_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221007124919_add_org_id.sql
  teamA/crud-express/heeyeon/db/migrations/20221010111616_add_org_id.sql
  teamA/crud-express/heeyeon/db/migrations/20221010112346_add_org_id.sql
  teamA/crud-express/heeyeon/db/schema.sql
  teamA/crud-express/heeyeon/package-lock.json
  teamA/crud-express/heeyeon/package.json
Labels: 멘토 리뷰 요청

#33 [김희연-teamA] Assignment 2: Express API - 유저 회원가입 하기
  teamA/crud-express/heeyeon/.env.sample
  teamA/crud-express/heeyeon/.gitignore
  teamA/crud-express/heeyeon/app.js
  teamA/crud-express/heeyeon/db/migrations/20221006181716_create_users_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181725_create_posts_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181733_create_comments_table.sql
  teamA/crud-express/heeyeon/db/migrations/20221006181738_create_likes_table.sql
  teamA/crud-express/heeyeon/db/schema.sql
  teamA/crud-express/heeyeon/package-lock.json
  teamA/crud-express/heeyeon/package.json
Labels: 수정 요청

#61 [신인혁-teamB] Assignment 3: Express API - CRUD
  teamB/shinInHuck/myapp/app.js
  teamB/shinInHuck/myapp/db/migrations/20221012074550_create_users_table.sql
  teamB/shinInHuck/myapp/db/migrations/20221012074555_create_posts_table.sql
  teamB/shinInHuck/myapp/db/migrations/20221012074622_create_likes_table.sql
  teamB/shinInHuck/myapp/package-lock.json
  teamB/shinInHuck/myapp/package.json
Labels: 멘토 리뷰 요청

#65 [김택수-teamA] Assignment 1: bcrypt
  teamA/kimTaeksoo/model/userDao.js
  teamA/kimTaeksoo/package-lock.json
  teamA/kimTaeksoo/package.json
  teamA/kimTaeksoo/service/userService.js
Labels: 멘토 리뷰 요청

#60 [김성훈-teamB] Assignment 4: Layered Pattern
  teamB/kimSungHoon/.env.sample
  teamB/kimSungHoon/app.js
  teamB/kimSungHoon/controllers/likeController.js
  teamB/kimSungHoon/controllers/postController.js
  teamB/kimSungHoon/controllers/userController.js
  teamB/kimSungHoon/db/migrations/20221007111233_create_users_table.sql
  teamB/kimSungHoon/db/migrations/20221007111246_create_posts_table.sql
  teamB/kimSungHoon/db/migrations/20221007111253_create_likes_table.sql
  teamB/kimSungHoon/db/migrations/20221007111303_create_comments_table.sql
  teamB/kimSungHoon/db/migrations/20221012123059_create_likes_table.sql
  teamB/kimSungHoon/models/likeDao.js
  teamB/kimSungHoon/models/moduleDao.js
  teamB/kimSungHoon/models/postDao.js
  teamB/kimSungHoon/models/userDao.js
  teamB/kimSungHoon/package.json
  teamB/kimSungHoon/routes/index.js
  teamB/kimSungHoon/routes/likeRouter.js
  teamB/kimSungHoon/routes/postRouter.js
  teamB/kimSungHoon/routes/userRouter.js
  teamB/kimSungHoon/services/likeService.js
  teamB/kimSungHoon/services/postService.js
  teamB/kimSungHoon/services/userService.js
Labels: 멘토 리뷰 요청
